# Generated by Django 2.1 on 2020-09-16 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Owner',
            fields=[
                ('PID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ABN', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Your_Own_Food',
            fields=[
                ('OID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Food_Origin', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('PID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Join_Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Feedback', models.CharField(max_length=400)),
                ('Preferred_Food_Type', models.TextField(choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Greek', 'Greek'), ('Other', 'Other')])),
                ('Card_Number', models.CharField(max_length=400)),
                ('Card_Exp_Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Card_CVV', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Card_Valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OID', models.CharField(max_length=6)),
                ('MID', models.CharField(max_length=6)),
                ('Changes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('MID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('MID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Ingredient', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Prepare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.CharField(max_length=6)),
                ('PID', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Payment_Method', models.TextField(choices=[('Online', 'Online'), ('In Store', 'In Srote')])),
                ('Status', models.TextField(choices=[('Preparing', 'Preparing'), ('Ready', 'Ready')])),
                ('Waiting_Time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OID', models.CharField(max_length=6)),
                ('PID', models.CharField(max_length=6)),
                ('Feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('PID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=400)),
                ('Last_Name', models.CharField(max_length=400)),
                ('Password', models.CharField(max_length=32)),
                ('Country', models.CharField(max_length=400)),
                ('City', models.CharField(max_length=400)),
                ('Email', models.CharField(max_length=400)),
                ('Contact_Number', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OID', models.CharField(max_length=6)),
                ('MID', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('MID', 'OID')},
        ),
        migrations.AlterUniqueTogether(
            name='order_feedback',
            unique_together={('OID', 'PID')},
        ),
        migrations.AlterUniqueTogether(
            name='menu_prepare',
            unique_together={('MID', 'PID')},
        ),
        migrations.AlterUniqueTogether(
            name='customize',
            unique_together={('MID', 'OID')},
        ),
    ]
