# Generated by Django 2.1 on 2020-09-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200920_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Food_Type',
            field=models.TextField(choices=[('Burgers', 'Burgers'), ('Wraps', 'Wraps'), ('Meal Options', 'Meal Options'), ('Snacks', 'Snacks')], default='Burgers'),
        ),
    ]
