# Generated by Django 2.1 on 2020-09-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_food_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Name',
            field=models.CharField(default='No Name', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='Name',
            field=models.CharField(max_length=30),
        ),
    ]
