# Generated by Django 2.1 on 2020-09-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200923_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Preferred_Food_Type',
            new_name='Preferred_Food_Taste',
        ),
        migrations.RemoveField(
            model_name='create_your_own_food',
            name='Food_Origin',
        ),
        migrations.AddField(
            model_name='create_your_own_food',
            name='Preferred_Food_Taste',
            field=models.TextField(choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Greek', 'Greek'), ('Other', 'Other')], default='Indian'),
            preserve_default=False,
        ),
    ]
