# Generated by Django 2.1 on 2020-09-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200930_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Card_CVV',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Card_Number',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Feedback',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Preferred_Food_Taste',
            field=models.TextField(choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Greek', 'Greek'), ('Other', 'Other')], default='Indian'),
        ),
    ]
