# Generated by Django 2.1 on 2020-09-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200930_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='MID',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='customer.Menu'),
        ),
    ]
