# Generated by Django 2.1 on 2020-09-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20200930_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='MID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Menu'),
        ),
    ]
